filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /host-logs-producto/*.log
    fields:
      service: producto-service
  - type: log
    enabled: true
    paths:
      - /host-logs-orden/*.log
    fields:
      service: orden-service
output.logstash:
  hosts: ["logstash:5044"]
