global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producto-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['producto-service:8083']
  - job_name: 'orden-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orden-service:8084']
